# Generated by Django 3.2 on 2022-03-26 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_content', models.TextField()),
                ('is_viewed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('abstractletter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='letters.abstractletter')),
                ('has_response', models.BooleanField(default=False)),
            ],
            bases=('letters.abstractletter',),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('abstractletter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='letters.abstractletter')),
                ('response_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letters.letter')),
            ],
            bases=('letters.abstractletter',),
        ),
    ]
