# Generated by Django 3.2 on 2022-03-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractletter',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
